export const Tables = {
    get USERS() { return process.env.USERS_TABLE!; },
    get ORGANIZATIONS() { return process.env.ORGANIZATIONS_TABLE!; },
    get MEMBERSHIPS() { return process.env.MEMBERSHIPS_TABLE!; },
    get TEAMS() { return process.env.TEAMS_TABLE!; },
    get INTEGRATIONS() { return process.env.INTEGRATIONS_TABLE!; },
    get INVOICES() { return process.env.INVOICES_TABLE!; },
    get INVOICE_PAYMENTS() { return process.env.INVOICE_PAYMENTS_TABLE!; },
    get CLIENTS() { return process.env.CLIENTS_TABLE!; },
    get JOBS() { return process.env.JOBS_TABLE!; },
    get BOOKINGS() { return process.env.BOOKINGS_TABLE!; },
    get TIME_ENTRIES() { return process.env.TIME_ENTRIES_TABLE!; },
    get RECEIPTS() { return process.env.RECEIPTS_TABLE!; },
    get TRIPS() { return process.env.TRIPS_TABLE!; },
    get STATEMENTS() { return process.env.STATEMENTS_TABLE!; },
    get LEADS() { return process.env.LEADS_TABLE!; },
    get PIPELINES() { return process.env.PIPELINES_TABLE!; },
    get ADS() { return process.env.ADS_TABLE!; },
    get CONVERSATIONS() { return process.env.CONVERSATIONS_TABLE!; },
    get NOTIFICATIONS() { return process.env.NOTIFICATIONS_TABLE!; },
    get ORG_CHANNELS() { return process.env.ORG_CHANNELS_TABLE!; },
    get COMPLIANCE() { return process.env.COMPLIANCE_TABLE!; },
    get INBOX_CACHE() { return process.env.INBOX_CACHE_TABLE!; },
    get META_PAGE_MAPPINGS() { return process.env.META_PAGE_MAPPINGS_TABLE!; },
} as const;
